# Fastlane Constants
fastlane_version "2.55.0"
default_platform :ios

platform :ios do

  desc "Install pod dependencies"
  lane :install_pods do
    cocoapods
  end

  # before_all do
  #   ensure_git_status_clean
  # end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "WWDCast")
  end

  # Private

  def project_base_path
    File.expand_path("..", Dir.pwd)
  end

end